### ISSUE TITLE
Add Handler.understands to move message parsing to handlers

### ISSUE THREAD

**Issue by rizqidjamaluddin** [thomasruiz/liz#1]
Let's change it up so messages don't have a predetermined `Message.type` and, instead, they get piped to each handler until it finds one that accepts it.

So instead of 

```
.then((message: Message) => this.handlers[message.type].handle(message))
```

We do

```
.then((message: Message) => {
    for(let handler of this.handlers) {
        if (handler.understands(message)) {
            handler.handle(message)
            break;
        }
    }
})
```

This would mean that higher-up handlers in the list would gain priority.

**Comment by thomasruiz** [comment]
@rizqidjamaluddin yup, it's clearer like that. Thanks!
